name: CDILand
main: fr.citedesiles.cdiland.CDILandPlugin
version: 1.0
author: Azrotho
api-version: 1.21
depend:
  - FancyNpcs
  - FancyHolograms
commands:
  admin:
    description: Admin command
    usage: /admin